# Generated by Django 4.0.3 on 2022-03-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('driver_age', models.IntegerField()),
                ('driver_gender', models.CharField(max_length=25)),
                ('driver_employment', models.CharField(max_length=25)),
                ('driver_marital', models.CharField(max_length=25)),
                ('driver_location', models.CharField(max_length=25)),
                ('vehicle_age', models.IntegerField()),
                ('vehicle_model', models.CharField(max_length=25)),
                ('insurance_premium', models.FloatField()),
                ('insurance_claims', models.FloatField()),
                ('insurance_losses', models.FloatField()),
            ],
        ),
    ]
